-- CreateEnum
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "ExchangeType" AS ENUM ('DROP_OFF', 'PICK_UP', 'INVENTORY_CORRECTION');

-- CreateTable
CREATE TABLE "Visitor" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "studentId" STRING,
    "gender" "Gender" NOT NULL,
    "major" STRING NOT NULL,
    "college" STRING NOT NULL,
    "level" STRING NOT NULL,
    "class" STRING NOT NULL,

    CONSTRAINT "Visitor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ItemExchange" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" "ExchangeType" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "visitorId" INT4,
    "bags" INT4 NOT NULL DEFAULT 0,
    "belts" INT4 NOT NULL DEFAULT 0,
    "books" INT4 NOT NULL DEFAULT 0,
    "dresses" INT4 NOT NULL DEFAULT 0,
    "hats" INT4 NOT NULL DEFAULT 0,
    "household" INT4 NOT NULL DEFAULT 0,
    "jacket" INT4 NOT NULL DEFAULT 0,
    "longSleeve" INT4 NOT NULL DEFAULT 0,
    "pants" INT4 NOT NULL DEFAULT 0,
    "jewelry" INT4 NOT NULL DEFAULT 0,
    "schoolSupplies" INT4 NOT NULL DEFAULT 0,
    "shirts" INT4 NOT NULL DEFAULT 0,
    "shoes" INT4 NOT NULL DEFAULT 0,
    "shorts" INT4 NOT NULL DEFAULT 0,
    "skirt" INT4 NOT NULL DEFAULT 0,
    "sunglasses" INT4 NOT NULL DEFAULT 0,
    "sweater" INT4 NOT NULL DEFAULT 0,
    "tankTop" INT4 NOT NULL DEFAULT 0,
    "tie" INT4 NOT NULL DEFAULT 0,
    "misc" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "ItemExchange_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Visitor_studentId_key" ON "Visitor"("studentId");

-- AddForeignKey
ALTER TABLE "ItemExchange" ADD CONSTRAINT "ItemExchange_visitorId_fkey" FOREIGN KEY ("visitorId") REFERENCES "Visitor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
